export const INCREASE_COUNTER = 'INCREASE_COUNTER',
	DECREASE_COUNTER = 'DECREASE_COUNTER',
	RESET_COUNTER = 'RESET_COUNTER',
	RESET_INPUTS = 'RESET_INPUTS',
	SET_TEXT = 'SET_TEXT',
	SET_NUMBER = 'SET_NUMBER';
